name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "1.0.0"
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    env:
      NODE_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Make jest executable
        run: chmod +x node_modules/.bin/jest
      - name: Install dependencies
        run: npm install
      - name: Running Tests Backend
        run: npm test
      - name: Running Render Deploy
        if: github.ref == 'refs/heads/main' && success()
        run: |
          curl "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

  frontend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Running Frontend
        run: npm run build
